### PR TITLE
Add exception handling for empty wfm data

### LINKED ISSUE #21: exception when no data is available
For 4 Series, 5 Series and 6 Series oscilloscopes, the curve feature raises an exception if there is no data available to download.

### PR DESCRIPTION
**Pull request by trelkins3**
Fixes #21 by adding try-except block on reading the data for 4/5/6 series scopes.

Please test on your own scopes. @zkoppert - I've been having a hard time repeating this error, so if you could check this fix that would be lovely.

This is my last Hacktoberfest PR! :)

### CODE REVIEW

**Comment by cwstryker** [comment]
The proposed approach seems reasonable.   However, there are two changes that are needed:

1) The try, expect block should be silent, so no error messages should be displayed.  If there is no data to download from the instrument, the call to curve() should simply return an empty WaveformCollection object.
2) When used with an actual instrument, the call to _get_data() actually fails at a different, earlier location.  Here is an actual traceback produced when attempting to get the curve from CH2 when the channel has no data:

>>> osc.curve()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\curvequery\api_types.py", line 116, in __call__
    return self.action_fcn(instr, *args, **kwargs)
  File "\curve_query\src\curvequery\_tek_series_mso.py", line 86, in action_fcn
    instr, self._list_sources(instr), **kwargs
  File "\curvequery\_tek_series_mso.py", line 194, in _get_data
    x_scale = self._get_xscale(instr)
  File "\curvequery\_tek_series_mso.py", line 117, in _get_xscale
    pre = WaveformOutPre(*tuple(instr.query("WFMOutpre?").strip().split(";")))
TypeError: __new__() takes 21 positional arguments but 22 were given

I might consider moving your try, except block to call to _get_xscale().

**Comment by trelkins3** [comment]
To confirm: I am still planning on fixing this. I may need help to replicate the errors reported above.

**Comment by cwstryker** [comment]
I would happy to test any changes to submit to the PR.

**Comment by cwstryker** [comment]
I fixed this issue in a different PR.

**Pull request closed without merging**
